version: '3'
services:
    postgres:
        image: postgres
        container_name: budgets
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: budgets
            POSTGRES_PASSWORD: budgets
        volumes:
            - ./postgres:/var/lib/postgresql/data
